---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: generic-pipeline-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision sha
    - name: jwt_token
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun 
      metadata: 
        name: generic-build-$(tt.params.gitrevision)
      spec:
        taskRunSpecs:
          - pipelineTaskName: build
            computeResources:
              requests:
                cpu: 2
        serviceAccountName: openshift-pipelines
        pipelineRef: 
          name: generic-build-pipeline
        params: 
          - name: IMAGE_TAG
            value: $(tt.params.gitrevision)
          - name: JWT_TOKEN
            value: $(tt.params.jwt_token)
        podTemplate:
          securityContext:
            runAsUser: 1000
            fsGroup: 65532
            fsGroupChangePolicy: "OnRootMismatch"
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: acs-token
            secret:
              secretName: acs-token
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: pipeline-listener
spec:
  triggers:
    - name: filter-events
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
            - name: "overlays"
              value:
                - key: truncated_sha
                  expression: "body.after.truncate(7)"
      bindings:
        - name: gitrevision
          kind: TriggerBinding
          value: $(extensions.truncated_sha)
        - name: jwt_token
          kind: TriggerBinding
          value: $(body.after)
      template:
        ref: generic-pipeline-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-binding
spec:
  params:
    - name: gitrevision
      value: "$(body.after)"
    - name: jwt_token 
      value: "$(body.jwt_token)"