apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: compile
  labels:
    app.kubernetes.io/version: "0.7"
  annotations:
    tekton.dev/categories: Dependencies
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: compile
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
    tekton.dev/displayName: compile
spec:
  description: >-
    Fetches Dependencies &
    Builds GoLang Binary
  workspaces:
  - name: source
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"

  steps:

    - name: compile
      image: golang:1.20
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash

        mkdir -p /workspace/source/bin
        cd /workspace/source/src

        go mod download
        go build -o /workspace/source/bin/main main.go

        ls -la /workspace/source/bin/
