apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-scan
spec:
  description: >-
    Needs new description
  workspaces:
    - name: source
  steps:

    - name: check-scan
      image: registry.access.redhat.com/ubi9/ubi:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        cat scan_output.json
