name: Trigger on push

on:
  push:
    paths-ignore:
      - '.tekton/**'
      - 'pipelines/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Auth JWT
        id: get-jwt
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          RESPONSE=$(curl -X POST ${AUTH_URL} \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&grant_type=client_credentials")

          TOKEN=$(echo "${RESPONSE}" | jq -r '.access_token')

          echo "::set-output name=jwt_token::${TOKEN}"

      - name: Repack the Payload
        id: payload
        env:
          TEKTON_API_URL: ${{ secrets.TEKTON_API_URL }}
          JWT_TOKEN: ${{ steps.get-jwt.outputs.jwt_token }}
        run: |
          echo '${{ toJson(github.event) }}' > event-payload.json
          echo "::set-output name=event::$(\
            jq --arg jwt "$JWT_TOKEN" '. + {jwt_token: $jwt}' event-payload.json)"

      - name: Trigger the Webhook
        env:
          EVENT_PAYLOAD: ${{ steps.payload.outputs.event }}
        run: |
          echo "${EVENT_PAYLOAD}"
