name: Trigger on push

on:
  push:
    paths-ignore:
      - '.tekton/**'
      - 'pipelines/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Call GitHub API
      #   env:
      #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
          # curl -X GET -H "Authorization: Bearer $TOKEN" https://api.github.com/repos/${{ github.repository }}

      # - name: Retrieve OpenShift Login Token
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |

      - name: Authenticate and set context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Basic $(echo -n 'Ov23ligI7Qs9mfLN9wVu:8d24d40638dcfa1082580f0e6e10ae40c3ca8b77' | base64)" \
            -H "Accept: application/json" \
            -d "client_id=Ov23ligI7Qs9mfLN9wVu" \
            -d "client_secret=8d24d40638dcfa1082580f0e6e10ae40c3ca8b77" \
            -d "grant_type=urn:ietf:params:oauth:grant-type:device_code" \
            -d "device_code=$GITHUB_TOKEN" \
            https://github.com/login/oauth/access_token
