name: Trigger on push

on:
  push:
    paths-ignore:
      - '.tekton/**'
      - 'pipelines/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Call GitHub API
      #   env:
      #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     curl -X GET -H "Authorization: Bearer $TOKEN" https://api.github.com/repos/${{ github.repository }}

      # - name: Retrieve OpenShift Login Token
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |

      - name: Authenticate and set context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc
          ./oc version


          # openshift_server_url: "https://api.quay-demo-2.ot31.p1.openshiftapps.com:6443"
          # openshift_token: $GITHUB_TOKEN